### PR TITLE
Use hour12: false for Node.js 10 when hourCycle: 'h23' not available

### PR DESCRIPTION
**Pull request by mjradwin**

### CODE REVIEW

**Comment by calvinckho** [comment]
@mobz, any timeline on when you will merge the PR? Thanks.

**Comment by RoelRoel** [comment]
When will this be published on npm?

**Comment by mobz** [comment]
@mjradwin I thought I tested this in Node > 12 (or maybe a much later) and if hour12 and hourCycle are both defined it uses hour12 by default but then uses a default value for hourCycle which is wrong in some locations.

Can you confirm this fix working in Node 10, 12 70ish and 80+

See specifically issues/1 and the fix, which is the opposite of this.

I think it may need a test like if(hourCycle is avilable) { use hourCycle) else { use hour12 )

**Comment by mjradwin** [comment]
You're correct; I just tested, and my patch is NOT working correctly. I don't know why I thought it was.

**Comment by mobz** [comment]
I have implemented a cross-bug fix so the new version work regardless of whether the engine implements the buggy version of ecmascript/Intl of not

**Pull request closed without merging**
